FROM golang:1.17-alpine AS builder


RUN apk update && apk add git && apk add ca-certificates

WORKDIR /build

COPY ./go.mod go.mod
COPY ./go.sum go.sum

RUN go mod download

COPY . .

RUN go build  -o . ./...